---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: application
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: application
subjects:
- kind: ServiceAccount
  name: application
  namespace: kube-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: application
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: application
  namespace: kube-system
---
  ---
    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: application
      namespace: kube-system
      labels:
        name: application
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: application
        spec:
          serviceAccountName: application
          nodeSelector:
            beta.kubernetes.io/arch: amd64
          tolerations:
          - operator: Exists
            effect: NoSchedule      
          containers:
            - name: application
              image: gsakun/application:20200321
              imagePullPolicy: Always
              env:
                - name: REDIS_SERVER
                  value: redis.default.svc:6379
                - name: AUTHN_ENDPOINT
                  value: http://10.10.111.92:32305
                - name: AUTHN_REALM
                  value: service
