name: Build & Deploy

on: [push]

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag application 

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_PASSWD }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=gsakun/application
          echo "HELLO"
          echo IMAGE_ID=$IMAGE_ID
          VERSION=`date "+%Y%m%d"`
          docker tag application $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION 
  
      - name: Log into quay registry
        run: docker logout && echo "${{ secrets.QUAY_DOCKERHUB_PASSWD }}" | docker login quay.io -u "${{ secrets.QUAY_DOCKERHUB_USER }}" --password-stdin
  
      - name: Push image to quay.io
        run: |
          IMAGE_ID=quay.io/gsakun/application
          echo "HELLO"
          echo IMAGE_ID=$IMAGE_ID
          VERSION=`date "+%Y%m%d"`
          docker tag application $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Log into github registry
        run: docker logout && echo "${{ secrets.DOCKERHUB_PASSWD }}" | docker login docker.pkg.github.com -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
    
      - name: Push image to github
        run: |
          IMAGE_ID=docker.pkg.github.com/gsakun/application/application
          echo "HELLO"
          echo IMAGE_ID=$IMAGE_ID
          VERSION=`date "+%Y%m%d"`
          docker tag application $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION